- features/andes/org.wso2.carbon.andes.server.feature/pom.xml
- features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
- features/andes/org.wso2.carbon.andes.server.feature/resources/conf/qpid-config.xml
- features/andes/org.wso2.carbon.andes.server.feature/resources/conf/qpid-virtualhosts.xml
- pom.xml
- New configuration values for MQTT ring buffers in broker.xml.
- poms updated for Disruptor update.
> Disruptor upgrade to version 3.3.0.wso2v1

- pom.xml
Updated carbon commons version to 4.3.6. This incorporates fixes from https://github.com/wso2/carbon-commons/pull/56
> Updated carbon commons version to 4.3.6

- components/andes/org.wso2.carbon.andes/pom.xml
- components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java
- components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/listeners/AndesServerShutDownListener.java
Server shutdown order modified to avoid unnecessary exceptions like HazelcastInstanceNotActive exception
> Fix Jiras 964 and 970

- components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java
This pr is related to following jira issue[1]. this will add meaningful log info when displaying amqp host address and port while start up the server.
[1] https://wso2.org/jira/browse/MB-1077
> [MB-1077] add meaningful log message with amqp host address/port.

- components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/Utils.java
- components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java
- components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/service/QpidServiceImpl.java
- features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
This PR will fix following issues.
1. Added bind addresses per each transport. This change will enable AMQP and MQTT use separate bind addresses. There won't be a single bind address per server after this change[1].
2. Change AMQP and MQTT bind addresses 0.0.0.0 to bind all interfaces available[2].
[1] https://wso2.org/jira/browse/MB-1159
[2] https://wso2.org/jira/browse/MB-1124
> [MB-1159][MB-1124] bind address per transport related fixes

- components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/Utils.java
- components/andes/org.wso2.carbon.andes.ui/src/main/java/org/wso2/carbon/andes/ui/UIUtils.java
- components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/service/QpidServiceImpl.java
- features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
- features/andes/org.wso2.carbon.andes.server.feature/resources/conf/qpid-config.xml
This is with reference to jiras : 
https://wso2.org/jira/browse/MB-924 
https://wso2.org/jira/browse/MB-1160
AMQP SSL configurations are now parsed through AndesConfiguration instead of ServerConfiguration (QPID code.)
Dependent on : https://github.com/wso2/andes/pull/219
> Moving SSL configurations from qpid-config.xml to broker.xml

- features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
We brought 3 TopicMessage delivery strategies
<topicMessageDeliveryStrategy>
<strategyName>DISCARD_NONE </strategyName>
<deliveryTimeout>60</deliveryTimeout>
</topicMessageDeliveryStrategy>	
Default strategy is "DISCARD_NONE".
> Add topic delivery strategies

- components/andes/org.wso2.carbon.andes.authentication/src/main/java/org/wso2/carbon/andes/authentication/andes/CarbonBasedMQTTAuthenticator.java
Add tenant support for MQTT authentication. 
Since carbon identifies a username in the format of username@domain and since MB expects a username in the format username!domain, this conversion was needed.
> Add tenant support for MQTT.

- features/andes/org.wso2.carbon.andes.server.feature/resources/dbscripts/h2-mb.sql
- features/andes/org.wso2.carbon.andes.server.feature/resources/dbscripts/mssql-mb.sql
- features/andes/org.wso2.carbon.andes.server.feature/resources/dbscripts/mysql-mb.sql
Some of the queue name declarations in the sql scripts had a length that is incompatible with the other declarations.
addresses the jira https://wso2.org/jira/browse/MB-1168
> Changed script so that queue name declarations have the same length

- components/andes/org.wso2.carbon.andes.ui/src/main/java/org/wso2/carbon/andes/ui/client/QueueSenderClient.java
- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_message_sender.jsp
Addresses the jira https://wso2.org/jira/browse/MB-1226
The issue was caused by intentionally setting JMS delivery mode to 1 when a user publishes messages through the management console without deliberately setting the JMS delivery mode.
> [MB-1226] Set UI message sender's JMS delivery mode to 2

- components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/subscription/registry/TopicManagerServiceImpl.java
- carbon.super prefix added to role name when subscribe to topic in super tenant with PR #151. So it has modified to check whether subscriber from super tenant or not. If subscriber from super tenant, then no tenant prefix added to role name. Else tenant domain prefix added to role name.
> MB-1269 alteration made to previous fix

- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/js/treecontrol.js
- Public jira url https://wso2.org/jira/browse/MB-1377. We create queue name with tmp_ prefix when non durable topic subscription added. Queue name with tmp_ prefix filtered in management console and not listing under queue. So as a fix, we are not allow to create queue name with tmp_ prefix.
> MB-1377 issue fixed.

- components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java
- components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/service/QpidServiceImpl.java
Open MQTT related ports as required when  SSL enabled/ disabled from broker configuration. 
This PR is dependent on https://github.com/wso2/andes/pull/382
https://wso2.org/jira/browse/MB-1339
> [MB-1339] open ports as required when ssl enabled or disabled.

- components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/topics.jsp
Publishing messages in root topic should be avoided as root topic "/ " is not a topic and the user will be confused with the success popup shown for the published message.
> [MB-1364] Remove message publish area in root topic

- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp
Addresses the issue reported at https://wso2.org/jira/browse/MB-1418.
The issue was caused by the same page number being used for all active temporary topic subscriptions, active durable subscriptions and inactive durable subscriptions.
> [MB-1418] Fixed topic subscription pagination issue

- components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
- components/andes/org.wso2.carbon.andes.commons/src/main/java/org/wso2/carbon/andes/commons/registry/RegistryClient.java
- components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java
- components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/subscription/registry/TopicManagerServiceImpl.java
- Admin user allow to proceed with any operation. But issue mentioned in jira has problem with super tenant admin user created topic/durable topic could access to tenant admin user. This has avoid by granting permission for that particular topic/durable topic to admin user role of particular tenant.
- Previously we create internal role when create queue/topic by admin user. This has avoid with this because admin user by default allow to proceed with any operation.
> MB-1441 issue fixed.

- components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/listeners/MessageBrokerTenantManagementListener.java
Since the tenant create notification is only received to a single
node, we can initialize the DLC without checking if coordinator.
https://wso2.org/jira/browse/MB-1469
> [MB-1469] [Tenant] DLC page not accessible in clustered environment

- components/andes/org.wso2.carbon.andes.commons/src/main/java/org/wso2/carbon/andes/commons/CommonsUtil.java
- Public jira url https://wso2.org/jira/browse/MB-1496
We are currently supported wildcard like topicOrSubtopicName.* or topicOrSubtopicName.# and permission model working for subscription like that. If you create subscription like *.topicOrSubtopicName, then it it will cause to permission denied and even you subscribe with admin user, messages are not getting routed to destination. We will improve subscription like *.topicOrSubtopicName in future release.
> MB-1496 issue fixed.

- components/andes/org.wso2.carbon.andes.commons/pom.xml
- components/andes/org.wso2.carbon.andes.commons/src/main/java/org/wso2/carbon/andes/commons/registry/RegistryClient.java
- components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/Utils.java
- components/andes/org.wso2.carbon.andes.event.core/pom.xml
- components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/subscription/registry/TopicManagerServiceImpl.java
- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/js/treecontrol.js
Changes related to queue/topic names:
MB-1386 : Queue/Topic names should be trimmed before saving
MB-1391 : If a message is published from UI to a topic with a name which has a space in-between the message is not routed to the subscribers
MB-1427 : Prevent topic creation which has two full stops subsequently e.g - Sports..
MB-1455 : Queue names which has the " / " is not shown in UI
MB-1470 : "Cannot access the config registry" error message is displayed when trying to create a topic with *, # characters 
This fix validates queue/topic names, when creating queues/topics from UI.
As said in the AMQP specification, this PR allows only alphanumeric, '.', '*' and '#' characters when creating topics. Also, prohibited space and the tenant separator '/', when creating queues. 
Please merge with: …
> MB-1386, MB-1391, MB-1427, MB-1455, MB-1470

- components/andes/org.wso2.carbon.andes.admin/src/main/resources/META-INF/services.xml
The operation getQueueByName was only given parent permission. Corrected that to have all 
/permission/admin/manage/queue/add
/permission/admin/manage/queue/browse
/permission/admin/manage/queue/purge
/permission/admin/manage/queue/delete
> Permission corrected for the operation to get queue

- pom.xml
Upgraded multitenancy, registry and commons versions.
multitenancy-4.4.4 requires registry-4.5.0 and commons-4.4.8
> multitenancy-4.4.4, registry-4.5.0 and commons-4.4.8 upgrade

- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_delete_ajaxprocessor.jsp
- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp
Addresses the issue reported at https://wso2.org/jira/browse/MB-1533
The issue occurred since the the check for active subscriptions upon a queue delete request was only done for queues but not for topics.
> [MB-1533] Added error dialog when unable to unsubscribe active durable subscriptions

- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp
Fixing https://wso2.org/jira/browse/MB-1576
Now DLC queue does not display "redelivered" and "deliverymode" pages.
> removed unnecessary columns on DLC page

- components/andes/src/main/java/org/wso2/carbon/andes/core/AndesEncodingUtil.java
- components/andes/src/main/java/org/wso2/carbon/andes/core/AndesUtils.java
- components/andes/src/main/java/org/wso2/carbon/andes/core/internal/slot/SlotDeliveryWorker.java
Define character encoding to UTF-8. Otherwise, it will default to system default encoding which is not recommended. 
This issue was reported by findbugs under DM_DEFAULT_ENCODING category.
> [MB-1722] DM_DEFAULT_ENCODING Fix undefined character encoding issue.

- components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
- isDurableTopicSubscriberQueue() method removed since there is no usage with it now. We always set internal queue name of durable subscription as virtual host:subscription id. Previously we set it as client id:subscription id.
- https://wso2.org/jira/browse/MB-1800
> MB-1800 issue fixed.

- components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
- Public JIRA URL https://wso2.org/jira/browse/MB-1783. The fix is to compel subscription id pattern as {tenant_domain}/{subscription_id} when adding durable subscription to sub-tenant. Otherwise, connection will end up in permission denied the exception.
> MB-1783 issue fixed.

- components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java
- components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/QueueManagementBeans.java
- components/andes/org.wso2.carbon.andes.event.admin/src/main/java/org/wso2/carbon/andes/event/admin/AndesEventAdminService.java
Queue names are turned to lower case when admin services are called as required for the change in https://github.com/wso2/andes/pull/831
Test case added in https://github.com/wso2/product-mb/pull/468
> Made queue names case insensitive

- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp
Remove subscription id prefix from the subscription list page. Due to this, filtering logic not working when do search by ID.
> MB-1891 issue fixed.

- features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Removed configuration in broker.xml to pick either Hazelcast slot agent or database slot agent. The changes in the classes are done in https://github.com/wso2/andes/pull/852 and seriaizer definitions are removed from axis2.xml in https://github.com/wso2/product-mb/pull/474
> Removed hazelcast based slot agent configuration

- components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java
- components/andes/org.wso2.carbon.andes.admin/src/main/resources/META-INF/services.xml
- components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerService.java
- components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java
- components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/QueueManagementBeans.java
- components/andes/org.wso2.carbon.andes.ui/src/main/resources/AndesAdminService.wsdl
- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_message_reroute_ajaxprocessor.jsp
- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_message_restore_ajaxprocessor.jsp
- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp
- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_messages_ids_ajaxprocessor.jsp
- service-stubs/org.wso2.carbon.andes.stub/src/main/resources/AndesAdminService.wsdl
provides 2 new Admin services with regard to DLC operations within the server.
1. getMessageMetadataInDeadLetterChannel
Returns a paginated list of message metadata destined for the targetQueue but currently living in the
Dead Letter Channel.
@param targetQueue    Name of the destination queue
@param startMessageId Start point of the queue message id to start reading
@param pageLimit      Maximum number of messages required in a single response
2. rerouteAllMessagesFromDeadLetterChannelForQueue
Move messages destined for the input sourceQueue into a different targetQueue.
If the sourceQueue is DLCQueue, all messages in the DLC will be restored to the targetQueue.
@param sourceQueue       Name of the source queue
@param targetQueue       Name of the target queue.
@param internalBatchSize …
> [MB-1737] - retrieve DLC messages without content for admin service purposes

- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp
This issue related to view message content of DLC. 'more..' link submit a POST request to backend but CSRF token missing on the last record. As a result, it ends up in forbidden page. The fix is to add CSRF token as hidden value in the form.
> Fix MB-1935

- components/org.wso2.carbon.business.messaging.core/src/main/java/org/wso2/carbon/business/messaging/core/internal/BrokerServiceComponent.java
- features/org.wso2.carbon.business.messaging.core.feature/resources/conf/broker.xml
- features/org.wso2.carbon.business.messaging.core.feature/src/main/resources/conf/broker.xml
We now have two options for "deployment/mode". They are,
- **standalone** - This is the simplest mode a broker can be started. The node will assume that message store is not shared with another node. Therefore it will not try to coordinate with other nodes (possibly non-existent) to provide HA. This is the default configuration used.
- **clustered** - Broker node will run in HA mode (active/passive).
> Change deployment configurations

- pom.xml
Upgrade Carbon-Kernel and related dependencies to latest
Following components are updated,
- Carbon-Kernel    5.2.0
- Carbon-Secvault    5.0.8
- Carbon-Metrics     2.3.2
- Carbon-Datasources 1.1.3
- Carbon-Jndi        1.0.4
- Carbon-Config      2.1.2
> Upgrade Carbon-Kernel to 5.2.0

- components/org.wso2.carbon.business.messaging.core/pom.xml
- components/org.wso2.carbon.business.messaging.core/src/main/java/org/wso2/carbon/business/messaging/core/authentication/AuthenticationService.java
- components/org.wso2.carbon.business.messaging.core/src/main/java/org/wso2/carbon/business/messaging/core/authentication/CarbonBasedPrincipalDatabase.java
- components/org.wso2.carbon.business.messaging.core/src/main/java/org/wso2/carbon/business/messaging/core/exceptions/AuthenticationException.java
- components/org.wso2.carbon.business.messaging.core/src/main/java/org/wso2/carbon/business/messaging/core/internal/AuthenticationServiceImpl.java
- components/org.wso2.carbon.business.messaging.core/src/main/java/org/wso2/carbon/business/messaging/core/internal/BrokerCoreBundleActivator.java
- components/org.wso2.carbon.business.messaging.core/src/main/java/org/wso2/carbon/business/messaging/core/internal/BrokerServiceComponent.java
- components/org.wso2.carbon.business.messaging.core/src/main/java/org/wso2/carbon/business/messaging/core/internal/BrokerServiceDataHolder.java
- features/org.wso2.carbon.business.messaging.core.feature/src/main/resources/conf/broker.xml
- features/org.wso2.carbon.business.messaging.core.feature/src/main/resources/conf/qpid-config.xml
This exposes AuthenticationService interface as an OSGI service where external components can register implementations.To support multiple implementations BrokerServiceComponent is updated as a capabilityListener, which would hold broker start-up until all registered implementations for AuthenticationService are available. Once all capabilities are available, it will match the implementation class name provided in broker.xml (<authenticator class="'/>) and set the correct implementation.
> Add authentication interface support for MB4. 

- test_artifacts/jmeter-samplers/src/main/java/org/wso2/jmeter/java/samplers/TransactedQueueReceiver.java
Remove redundant properties ( msgCount/message) which causes findbug error when building.
> Fix findbug error on unused properties in TransactedQueueReceiver.java

- pom.xml
CI/CD is disabled for 4.x.x branches. We will maually realease them for the
moment. Hence to ease development, updating the dependency.
> Update pom.xml to have Andes-SNAPSHOT version

- components/andes/org.wso2.carbon.andes.cluster.mgt.ui/pom.xml
- components/andes/org.wso2.carbon.andes.event.ui/pom.xml
- components/andes/org.wso2.carbon.andes.ui/pom.xml
- pom.xml
> To be compatible with the EI broker profile we must keep the dependencies up to date.
> Upgrading wso2 identity components to latest versions

- features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
> Add new configuration to broker. xml
```
<moveExpiredMessagesToDLC>false</moveExpiredMessagesToDLC>
```
> Fix ei-1914
> Modify the configuration to enable feature descried at the issue 
> N/A
> N/A
> https://docs.wso2.com/display/EI611/Implementing+Message+Expiration
This page should have the description. 
> N/A
> N/A. It is a small feature. 
> MB now supports moving expired messages to DLC. They are not lost. You can later route back to origin queue or a different queue. 
- Unit tests 
> Not added. Reused existing methods
- Integration tests
> Not added. Add when MB test suite is moved to EI
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR …
> Modify broker.xml to fix ei-1914

- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_message_destinations_list_retrieve_ajaxprocessor.jsp
- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp
- features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
- pom.xml
Enables the functionality of re-routing all messages that belong to a
queue by default as opposed to a configuration in broker.xml. Also
blocks the DLC queue from being listed under the queue list.
Resolves: https://github.com/wso2/product-ei/issues/2322
https://github.com/wso2/andes/pull/980
> Improve Re-route All in DLC

- components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/js/treecontrol.js
In the Dead Letter Channel browse view the filter should be applied in the format
carbon:[subscriptionID] which has a colon.
Ajax call breaks when get parameters contain special characters. Therefore the nameOfQueue is sent through post method data.
Fixes wso2/product-ei#3350
> Send nameOfQueue through post method instead of get

- components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java
- features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
- pom.xml
As we have deprecated the Hazelcast based distributed caching use cases in APIM, removing the Hazelcast dependency from carbon-business-messaging repository.
Fixes wso2/api-manager#475
> Remove Hazelcast

- pom.xml
Upgrades the protobuf-java version to non-vulnerable 3.25.5.
> [APIM 4.4.0] Upgrade protobuf-java version

- pom.xml
This PR upgrades the Andes version from 3.3.28 to 3.3.33 to reflect changes made in the following PR to the andes bundle
- Related PR https://github.com/wso2/andes/pull/1064
> [APIM][4.4.0] Upgrade Andes Version from 3.3.28 to 3.3.33
