components/andes/org.wso2.carbon.andes.admin/pom.xml, components/andes/org.wso2.carbon.andes.authentication/pom.xml, components/andes/org.wso2.carbon.andes.authorization/pom.xml, components/andes/org.wso2.carbon.andes.cluster.mgt.ui/pom.xml, components/andes/org.wso2.carbon.andes.cluster.mgt/pom.xml, components/andes/org.wso2.carbon.andes.commons/pom.xml, components/andes/org.wso2.carbon.andes.core/pom.xml, components/andes/org.wso2.carbon.andes.ui/pom.xml, components/andes/org.wso2.carbon.andes/pom.xml, components/andes/pom.xml, features/andes/org.wso2.carbon.andes.feature/pom.xml, features/andes/org.wso2.carbon.andes.server.feature/pom.xml, features/andes/org.wso2.carbon.andes.ui.feature/pom.xml, features/andes/pom.xml, pom.xml, service-stubs/org.wso2.carbon.andes.mgt.stub/pom.xml, service-stubs/org.wso2.carbon.andes.stub/pom.xml, service-stubs/pom.xml
Merge released branch to master for new development cycle
=> Release 2.5.0

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
Fixed invalid domain check when consuming a destination.
=> Fixed invalid domain check when handling destination consuming.

pom.xml
Modified parent pom.xml to target andes 3.0.0-SNAPSHOT
=> Modified parent pom.xml to target andes 3.0.0-SNAPSHOT

components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/Utils.java
Browsing and publishing messages for queues did not work through the UI as the the amqp url was hardcoded with "localhost". This was changed to pick up from AndesConfiguration(bindAddress in broker.xml).
JIRA - https://wso2.org/jira/browse/MB-923
=> Removed hardcoded localhost url when using browsing and publisher messages for queues through UI

components/andes/org.wso2.carbon.andes/pom.xml, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/MessageBrokerTenanatManagementListener.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java, pom.xml
Add Message Broker tenant management listener and invoke DLC queue creation when a tenant is created.
=> Add Message Broker tenant management listener

components/andes/org.wso2.carbon.andes/pom.xml, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/utils/DataSourceConfiguration.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/utils/LocalDatabaseCreator.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/utils/MessageBrokerDBUtil.java
This pull request contains dsetup feature for MB rdbms stores.
jira url -  https://wso2.org/jira/browse/MB-909
=> [MB-909] Added dsetup feature for mb rdbms stores.

features/andes/org.wso2.carbon.andes.server.feature/resources/dbscripts/oracle-mb.sql
fix for following jira.
https://wso2.org/jira/browse/MB-971
=> [MB-971] fix sql error when execute dsetup with oracle database.

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Added comment for H2 In-Memory mode in broker.xml as closing down the server would not store messages.
=> Added comment for H2 In-Memory mode in broker.xml

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.ui/src/main/java/org/wso2/carbon/andes/ui/UIUtils.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/update_queue_role_permissions_to_session_ajaxprocessor.jsp
Fixes for https://github.com/wso2/carbon-business-messaging/pull/10
=> Fixed JavaDocs and Comments.

components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/Utils.java, features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Added necessary constants and fixed readability.
=> Added necessary constants and fixed readability.

components/andes/org.wso2.carbon.andes.cluster.mgt.ui/src/main/java/org/wso2/carbon/andes/cluster/mgt/ui/ClusterManagerClient.java, features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Fixed comment in ClusterManagerClient.java.
=> Fixed comment in ClusterManagerClient.java.

features/andes/org.wso2.carbon.andes.server.feature/pom.xml, features/andes/org.wso2.carbon.andes.server.feature/resources/p2.inf, pom.xml
this PR contains changes required for following jira.
jira - https://wso2.org/jira/browse/MB-978
=> [MB-978] Generate h2 database using h2-mb.sql script.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
1. Added null check for user realm when deleting queue.
2. Added null check for user realm when purgin queue
=> Added null check for user real when deleting or purging a queue.

components/andes/org.wso2.carbon.andes.ui/src/main/resources/org/wso2/carbon/andes/ui/i18n/Resources.properties, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_details.jsp
Added "Click here for more details" tooltip for queue name in queue details.
=> [MB-650] Added tooptip for the queue name in queue details page in the UI.

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Fix for JIRA issue - https://wso2.org/jira/browse/MB-989
=> Config Added to broker.xml

components/andes/org.wso2.carbon.andes.admin/pom.xml, components/andes/org.wso2.carbon.andes.authentication/pom.xml, components/andes/org.wso2.carbon.andes.authorization/pom.xml, components/andes/org.wso2.carbon.andes.cluster.mgt.ui/pom.xml, components/andes/org.wso2.carbon.andes.cluster.mgt/pom.xml, components/andes/org.wso2.carbon.andes.commons/pom.xml, components/andes/org.wso2.carbon.andes.core/pom.xml, components/andes/org.wso2.carbon.andes.ui/pom.xml, components/andes/org.wso2.carbon.andes/pom.xml, components/andes/pom.xml, features/andes/org.wso2.carbon.andes.feature/pom.xml, features/andes/org.wso2.carbon.andes.server.feature/pom.xml, features/andes/org.wso2.carbon.andes.ui.feature/pom.xml, pom.xml, service-stubs/org.wso2.carbon.andes.mgt.stub/pom.xml, service-stubs/pom.xml
- move dependency version to property
- format pom.xml
=> pom.xml changes

components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java
Fix for jira : https://wso2.org/jira/browse/MB-771
Support to disable/enable amqp or mqtt transport listeners. 
*The configuration properties had been added in a previous PR to broker.xml
=> fix_mb_jira_771

components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java
Fixing compiler issue specific to java 1.6 related to PR : 43
Issue explanation : http://stackoverflow.com/questions/5666027/why-does-the-compiler-state-no-unique-maximal-instance-exists
=> Fix generics type detection issue specific to java 1.6

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
new configuration : persistence/storeHealthCheckInterval
default value : 10
=> [MB-926] Introducing a new configuration

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.admin/src/main/resources/META-INF/services.xml, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/retrive_message_count_for_subscriber_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp, service-stubs/org.wso2.carbon.andes.stub/src/main/resources/AndesAdminService.wsdl
JIRA - https://wso2.org/jira/browse/MB-1037
=> [MB-1037] Fixed refresh button for remaining messages per subscription.

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_queue_details.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_details.jsp
JIRA - https://wso2.org/jira/browse/MB-691
=> [MB-691] Fixed is DLC check in UI.

components/andes/org.wso2.carbon.andes.admin/pom.xml, components/andes/org.wso2.carbon.andes.cluster.mgt.ui/pom.xml, components/andes/org.wso2.carbon.andes.cluster.mgt/pom.xml, components/andes/org.wso2.carbon.andes.core/pom.xml, components/cassandra/org.wso2.carbon.cassandra.datareader/pom.xml, components/cassandra/org.wso2.carbon.cassandra.datareader/src/main/java/org/wso2/carbon/cassandra/datareader/cql/CassandraConfiguration.java, components/cassandra/org.wso2.carbon.cassandra.datareader/src/main/java/org/wso2/carbon/cassandra/datareader/cql/CassandraDataSourceConstants.java, components/cassandra/org.wso2.carbon.cassandra.datareader/src/main/java/org/wso2/carbon/cassandra/datareader/cql/CassandraDataSourceReader.java, components/cassandra/org.wso2.carbon.cassandra.datareader/src/main/java/org/wso2/carbon/cassandra/datareader/cql/util/CassandraDatasourceUtils.java, components/cassandra/org.wso2.carbon.cassandra.datareader/src/main/java/org/wso2/carbon/cassandra/datareader/hector/DataReaderConstants.java, components/cassandra/org.wso2.carbon.cassandra.datareader/src/main/java/org/wso2/carbon/cassandra/datareader/hector/DataReaderUtil.java, components/cassandra/org.wso2.carbon.cassandra.datareader/src/main/java/org/wso2/carbon/cassandra/datareader/hector/HectorBasedDataSourceReader.java, components/cassandra/org.wso2.carbon.cassandra.datareader/src/main/java/org/wso2/carbon/cassandra/datareader/hector/HectorConfiguration.java, components/cassandra/org.wso2.carbon.cassandra.datareader/src/test/java/org/wso2/carbon/cassandra/datareader/unittest/CQLDatasourceReaderTest.java, components/cassandra/org.wso2.carbon.cassandra.datareader/src/test/java/org/wso2/carbon/cassandra/datareader/unittest/HectorLDatasourceReaderTest.java, components/cassandra/org.wso2.carbon.cassandra.datareader/src/test/resources/cql-datasource-config.xml, components/cassandra/org.wso2.carbon.cassandra.datareader/src/test/resources/hector-datasource-config.xml, components/cassandra/org.wso2.carbon.cassandra.datareader/src/test/resources/master-datasources.xml, components/cassandra/pom.xml, features/andes/org.wso2.carbon.andes.server.feature/pom.xml, features/cassandra/etc/feature.properties, features/cassandra/org.wso2.carbon.cassandra.datareader.feature/pom.xml, features/cassandra/pom.xml, pom.xml
cassandra datareader component and feature implementation
=> carbon-business-messaging moves to java 7

features/andes/org.wso2.carbon.andes.server.feature/pom.xml
This is working in progress.
See mail wso2 dev : "[Dev] [MB] Ciphertools - To include or not to include"
JIRA : https://wso2.org/jira/browse/MB-924
=> [MB-924] Added username and password for H2 store.

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/QueueManagementBeans.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_details.jsp
JIRA - https://wso2.org/jira/browse/MB-1056
=> [MB-1056] Fixed UI error messages.

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
- public jira url : https://wso2.org/jira/browse/MB-1054
=> MB-1054 issue fixed.

components/andes/org.wso2.carbon.andes.cluster.mgt.ui/src/main/java/org/wso2/carbon/andes/cluster/mgt/ui/ClusterManagerClient.java, components/andes/org.wso2.carbon.andes.cluster.mgt.ui/src/main/resources/web/andes-cluster-mgt/nodesList.jsp, components/andes/org.wso2.carbon.andes.cluster.mgt.ui/src/main/resources/web/andes-cluster-mgt/styles/tree-styles.css, components/andes/org.wso2.carbon.andes.cluster.mgt/src/main/java/org/wso2/carbon/andes/cluster/mgt/ClusterManagerService.java, components/andes/org.wso2.carbon.andes.cluster.mgt/src/main/java/org/wso2/carbon/andes/cluster/mgt/internal/ClusterMgtConstants.java, components/andes/org.wso2.carbon.andes.cluster.mgt/src/main/java/org/wso2/carbon/andes/cluster/mgt/internal/managementBeans/ClusterManagementBeans.java, service-stubs/org.wso2.carbon.andes.mgt.stub/src/main/resources/AndesManagerService.wsdl
Added message store health check to show in UI.
=> Added message store health check to show in UI.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java, components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/service/andes/AndesAuthorizationPlugin.java
- public jira url : https://wso2.org/jira/browse/MB-1065
=> MB-1065 issue fixed.

components/andes/org.wso2.carbon.andes.cluster.mgt.ui/src/main/resources/web/andes-cluster-mgt/nodesList.jsp
=> Modified Node Details section UI.

components/andes/org.wso2.carbon.andes/pom.xml, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/utils/DataSourceConfiguration.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/utils/LocalDatabaseCreator.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/utils/MessageBrokerDBUtil.java, features/andes/org.wso2.carbon.andes.server.feature/resources/dbscripts/oracle-mb.sql, pom.xml
This PR will include code review changes and code improvements.
=> Code review changes and code improvements.

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
New configuration values added for Andes core support for different content chunk sizes.
Jiras:
https://wso2.org/jira/browse/MB-972
https://wso2.org/jira/browse/MB-1015
https://wso2.org/jira/browse/MB-1039
https://wso2.org/jira/browse/MB-1071
=> broker.xml file updated with new configurations

components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/service/QpidServiceImpl.java
JIRA - https://wso2.org/jira/browse/MB-1107
=> [MB-1107] - Qpid serivce to load host address from bind address in broker.xml

components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/utils/DataSourceConfiguration.java
Since xpath query been re-used move it to a constant string.
=> Move xpath query to seperate constant

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_list_retrieve_ajaxprocessor.jsp
Resolves the jira https://wso2.org/jira/browse/MB-1115
=> Added check to see if the list is empty when retrieved all queues

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/internal/Message.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/QueueManagementBeans.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/types/Message.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/AndesAdminService.wsdl, components/andes/org.wso2.carbon.andes.ui/src/main/resources/org/wso2/carbon/andes/ui/i18n/Resources.properties, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_details.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_messages_list.jsp, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java, features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml, service-stubs/org.wso2.carbon.andes.stub/AndesAdminService.wsdl, service-stubs/org.wso2.carbon.andes.stub/src/main/resources/AndesAdminService.wsdl
queue browse tombstone reading issue fixed in cassadra
please note that queue browse cause major response
delay when message store is cassandra depend on tombstone count
and this would cause to browser timeout depending on configuration.
=> queue browse pagination support added

components/andes/org.wso2.carbon.andes.authorization/pom.xml, features/andes/org.wso2.carbon.andes.server.feature/pom.xml, features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml, pom.xml
Jira: https://wso2.org/jira/browse/MB-1130
This change will also upgrade commons-configuration lib to latest ( v 1.10 at the time of change)
=> [MB-1130] Fix error based flow control for mssql drivers.

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/queue_subscriptions_list.jsp
JIRA - https://wso2.org/jira/browse/MB-1140
=> [MB-1140] Modified message count refresh in queue subscriptions page.

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Fix for https://wso2.org/jira/browse/MB-1102
=> Remove sendExpiredMessagesToDLC from broker.xml

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_messages_list.jsp
JIRA - https://wso2.org/jira/browse/MB-734.
=> [MB-734] Added null check to content-type on UI message browsing

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
This to fix https://wso2.org/jira/browse/MB-1083
=> [MB-1083] Add missing authorization condition when publishing

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_message_sender.jsp
JIRA - https://wso2.org/jira/browse/MB-1096
=> Remove 'Duration to expire (in ms)' from UI since we are not supporting message expiry

components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java
JIRA - https://wso2.org/jira/browse/MB-1080
=> [MB-1080] Modified internal role name when created by tenant.

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_messages_list.jsp, features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
-  Management console message browsing property name messageBatchSizeForBrowserSubscriptions
changed to messageBrowsePageSize with implementation changes made to browsing
=> existing property change in broker.xml

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_messages_list.jsp
JIRA - https://wso2.org/jira/browse/MB-939
=> [MB-939] Added html escape character in message browsing.

components/andes/org.wso2.carbon.andes.cluster.mgt.ui/src/main/resources/web/andes-cluster-mgt/nodesList.jsp
JIRA - https://wso2.org/jira/browse/MB-1090
=> Added column in node list table to show node coordination id

components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/QueueManagementBeans.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/org/wso2/carbon/andes/ui/i18n/Resources.properties, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_messages_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp
Addresses the jira https://wso2.org/jira/browse/MB-1171
Please merge https://github.com/wso2/andes/pull/249 along with this
=> Durable topic subscription message browsing added

pom.xml
Addresses the jira https://wso2.org/jira/browse/MB-1182
Upgraded the carbon kernel version from 4.4.0 to 4.4.1
Please merge https://github.com/wso2/andes/pull/278  and https://github.com/wso2/product-mb/pull/159 along with this
=> Updated to kernel 4.4.1

pom.xml
upgrade guava version used in andes.
jira: https://wso2.org/jira/browse/MB-1190
=> [MB-1190] Upgrade guava to lastest version

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Jira: https://wso2.org/jira/browse/MB-1198
=> [MB-1198] Adding configurations for message cache

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_details.jsp
JIRA - https://wso2.org/jira/browse/MB-1126
=> [MB-1126] Invoke delete queue if requested before showing queues on the UI.

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.admin/src/main/resources/META-INF/services.xml, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_details.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/styles/dsxmleditor.css, service-stubs/org.wso2.carbon.andes.stub/src/main/resources/AndesAdminService.wsdl
JIRA - https://wso2.org/jira/browse/MB-1076
Disables the publish message link in the UI if user has no publishing permissions,
=> [MB-1076] Check whether user has publish permission for queue in UI

components/andes/org.wso2.carbon.andes.authentication/src/main/java/org/wso2/carbon/andes/authentication/andes/CarbonBasedMQTTAuthenticator.java
JIRA - https://wso2.org/jira/browse/MB-1180
=> [MB-1180] Adding tenant flow for mqtt auths

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java
JIRA - https://wso2.org/jira/browse/MB-1225
=> [MB-1225] Setting topic name for topic subscriptions on UI.

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/update_queue_role_permissions_ajaxprocessor.jsp
JIRA - https://wso2.org/jira/browse/MB-1227
=> [MB-1227] Changed updated successful notification.

components/andes/org.wso2.carbon.andes.ui/src/main/resources/META-INF/component.xml
JIRA - https://wso2.org/jira/browse/MB-1233
=> [MB-1233] Changed menu order value for queue.

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/update_queue_role_permissions_ajaxprocessor.jsp
JIRA - https://wso2.org/jira/browse/MB-1229
=> [MB-1229] Fixed error message when updating queue

pom.xml
jira: https://wso2.org/jira/browse/MB-1250
=> [MB-1250] Upgrading carbon-identity and carbon-commons related bundles

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/internal/QueueRolePermission.java, components/andes/org.wso2.carbon.andes.admin/src/main/resources/META-INF/services.xml, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/types/QueueRolePermission.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/add_queue_and_assign_role_permissions_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/js/treecontrol.js, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/js/treecontrol.js, service-stubs/org.wso2.carbon.andes.stub/src/main/resources/AndesAdminService.wsdl
Addresses the issue reported at https://wso2.org/jira/browse/MB-1131
Please merge https://github.com/wso2/andes/pull/351 along with this.
=> [MB-1131]Combined methods create queue and add permission

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
JIRA - https://wso2.org/jira/browse/MB-1343
=> [MB-1343] Removing H2 In-Memory persistence store.

components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/js/treecontrol.js, components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/topic_manage.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_manage.jsp
- Public jira url https://wso2.org/jira/browse/MB-1350
=> MB-1350 issue fixed.

components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.event.admin/src/main/java/org/wso2/carbon/andes/event/admin/AndesEventAdminService.java, components/andes/org.wso2.carbon.andes.event.admin/src/main/resources/META-INF/services.xml, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/delivery/jms/JMSDeliveryManager.java, components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/topic_manage.jsp, components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/try_it_out_invoke_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/update_role_permissions_from_session_ajaxprocessor.jsp, service-stubs/org.wso2.carbon.andes.event.stub/src/main/resources/AndesEventAdminService.wsdl
- Web service added in AndesEventAdminService to publish message to topic
- Topic manage JSP page implementation change to call publish message to web service
- WS subscription section removed from topic manage JSP
=> andes event topic publish UI fixes.

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1354
=> dlc-filtering-issue-fixed

components/andes/org.wso2.carbon.andes.commons/src/main/java/org/wso2/carbon/andes/commons/registry/RegistryClient.java, components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/delete_topic_ajaxprocessor.jsp
- Public jira url https://wso2.org/jira/browse/MB-1288
=> MB-1288 issue fixed.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/subscription/registry/TopicManagerServiceImpl.java
- Public jira url https://wso2.org/jira/browse/MB-1269
=> MB-1269 issue fixed.

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Added a comment mentioning time unit of deliveryTimeout in broker.xml.
jira - https://wso2.org/jira/browse/MB-1230
=> [MB-1230] add comment for deliveryTimeout config in broker.xml

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
- Public jira url https://wso2.org/jira/browse/MB-1284
=> MB-1284 issue fixed.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
- Public jira url https://wso2.org/jira/browse/MB-1375
=> MB-1375 issue fixed.

components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/Utils.java
- Public jira url https://wso2.org/jira/browse/MB-1379
=> MB-1379 issue fixed.

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_messages_list.jsp
jira: https://wso2.org/jira/browse/MB-1388
=> [MB-1388] Removing unused class referance and usage

components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/CarbonEventBroker.java, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/EventPublisher.java, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/delivery/jms/JMSDeliveryManager.java
- Public jira url https://wso2.org/jira/browse/MB-1380
=> MB-1380 issue fixed.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/service/andes/AndesAuthorizationPlugin.java
- Public jira url https://wso2.org/jira/browse/MB-1390
https://wso2.org/jira/browse/MB-1392
This issue occurred due to before tenant get load, we try to get userRelam object of tenant. I have change it to load tenant first and then get userRelam.
=> MB-1390 and MB-1392 fixed.

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Changes related to https://wso2.org/jira/browse/MB-1230
Removed configurations in broker.xml
=> [MB-1230 Changed configurations related to JIRA MB-1230

components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/subscription/registry/TopicManagerServiceImpl.java
JIRA - https://wso2.org/jira/browse/MB-1298
=> [MB-1298] JMS subscription created time not showing in Topic UI bug fix

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
- Public jira url https://wso2.org/jira/browse/MB-1340, https://wso2.org/jira/browse/MB-1416
Qpid create queue when non durable topic and durable topic subscription added. So we have create role by that queue name and assign permission to consume and publish. But we can avoid creating role for these queues and only grant permission to resource path of queue. This fix made necessary changes to avoid creating role for these queues.
=> MB-1340 and MB-1416 issue fixed.

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/internal/Queue.java, components/andes/org.wso2.carbon.andes.admin/src/main/resources/META-INF/services.xml, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/QueueManagementBeans.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/QueueManagementConstants.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/Utils.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_queue_details.jsp, service-stubs/org.wso2.carbon.andes.stub/src/main/resources/AndesAdminService.wsdl
Addresses the changes made to the core by https://github.com/wso2/andes/pull/386 due to https://wso2.org/jira/browse/MB-1268
Please merge https://github.com/wso2/andes/pull/386 and https://github.com/wso2/product-mb/pull/213 along with this
=> [MB-1268] Implemented message count retrieval for all queues

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.admin/src/main/resources/META-INF/services.xml, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_list_retrieve_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_message_sender.jsp, service-stubs/org.wso2.carbon.andes.stub/src/main/resources/AndesAdminService.wsdl
This PR adds code review changes and code improvements.
=> Review changes

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp
Removed the diamond operator which caused the error.
=> Fixed UI test failure

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
- Public jira url - https://wso2.org/jira/browse/MB-1128
https://wso2.org/jira/browse/MB-1326
Non durable subscription has 3 invocation.
1. create - create tmp queue for non durable topic subscriber in amqp
2. bind - 2 bind call. First call to bind tmp queue. Second call to bind tmp queue and topic name.
3. consume - consume message from tmp queue.
We are creating permission resource path dynamically for tmp queue because in consume call we only get tmp queue name. We don't have mapping between tmp queue and topic. Therefore, we create permission for tmp queue and assign to role. This happen in high concurrency when subscription adding in two nodes and causes dead-lock in permisson table of carbon user-core. Implementation of creating permission for tmp queue is avoid with this fix and …
=> MB-1128 and MB-1326 issue fixed.

components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/Utils.java
Fixing https://wso2.org/jira/browse/MB-1267
=> Fix topic subscriptions tenant wise filtering for UI

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/Utils.java, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/subscription/registry/TopicManagerServiceImpl.java
- Public jira url https://wso2.org/jira/browse/MB-1379
=> MB-1379 re-opened issue fixed.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java, components/andes/org.wso2.carbon.andes.commons/src/main/java/org/wso2/carbon/andes/commons/registry/RegistryClient.java, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/subscription/registry/TopicManagerServiceImpl.java
- Public jira url https://wso2.org/jira/browse/MB-1416
Hierarchical topic subscription permission model changed as below with this changes.
Let's say there is hierarchical topic call country.state.city1. User who has publish and subscribe permission to country could able to publish and subscribe it's all child topics. We are allow wild card subscription like country.* or country.# with this change as well. But user who has permission only to child topic i.e. city1 couldn't publish or subscribe to country or country.state
=> MB-1416 issue fixed.

components/andes/org.wso2.carbon.andes.event.ui/pom.xml, components/andes/org.wso2.carbon.andes.event.ui/src/main/java/org/wso2/carbon/andes/event/ui/UIUtils.java, components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/delete_topic_ajaxprocessor.jsp, pom.xml
- Public jira url  https://wso2.org/jira/browse/MB-1323
=> MB-1323 issue fixed.

components/andes/org.wso2.carbon.andes.commons/src/main/java/org/wso2/carbon/andes/commons/CommonsUtil.java, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/util/JavaUtil.java, components/andes/org.wso2.carbon.andes.event.ui/src/main/java/org/wso2/carbon/andes/event/ui/UIUtils.java
- Public jira url https://wso2.org/jira/browse/MB-1424
=> MB-1424 issue fixed.

components/andes/org.wso2.carbon.andes.admin/src/main/resources/META-INF/services.xml, components/andes/org.wso2.carbon.andes.event.admin/src/main/resources/META-INF/services.xml, components/andes/org.wso2.carbon.andes.ui/pom.xml, components/andes/org.wso2.carbon.andes.ui/src/main/java/org/wso2/carbon/andes/ui/UIUtils.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/styles/dsxmleditor.css, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp
- Public jira url https://wso2.org/jira/browse/MB-1447
User who has topic delete and details permission could do unsubscribe and browse action in topic subscription page. So user who has only topic subscription permission can only view topic subscription details.
=> MB-1447 issue fixed.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
- Public jira url https://wso2.org/jira/browse/MB-1387
=> MB-1387 issue fixed.

components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java
Logs if tried to delete a non-existing queue.
=> [MB-1245] DurableTopicsSubscribers are not getting unsubscribed

components/andes/org.wso2.carbon.andes.admin/src/main/resources/META-INF/services.xml
Tracked by https://wso2.org/jira/browse/MB-1500
=> Fixed MB-1500

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
This pull fixes the following issues.
https://wso2.org/jira/browse/MB-1478
https://wso2.org/jira/browse/MB-1481
https://wso2.org/jira/browse/MB-1505
=> Authorize topics pub/sub if a parent level has permissions

components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/subscription/registry/TopicManagerServiceImpl.java
- Public jira url https://wso2.org/jira/browse/MB-1506
=> MB-1506 issue fixed.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/subscription/registry/TopicManagerServiceImpl.java
- Public jira url https://wso2.org/jira/browse/MB-1483 https://wso2.org/jira/browse/MB-1487
=> MB-1483 and MB-1487 issues fixed.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/subscription/registry/TopicManagerServiceImpl.java
- Public jira url https://wso2.org/jira/browse/MB-1486
=> MB-1486 issue fixed.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
- Public jira url https://wso2.org/jira/browse/MB-1532
=> MB-1532 issue fixed.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
- Public jira url https://wso2.org/jira/browse/MB-1483
=> MB-1483 issue fixed.

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/QueueManagementBeans.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_messages_list.jsp
Addresses the issue reported at https://wso2.org/jira/browse/MB-1511
=> [MB-1511] Removed delivery mode column from UI

components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/js/treecontrol.js, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/js/treecontrol.js
Addresses the issue reported at https://wso2.org/jira/browse/MB-1319
=> [MB-1319] - When "&" is in the queue or topic name, inconsistent behaviours were observed

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
This pull fixes https://wso2.org/jira/browse/MB-1505.
=> When giving permission to consume queue, provide permission to Durable Topic Queues

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Also made default recovery time task interval to 15 minutes.
=> moving vHostSyncTaskInterval under recovery tag

components/andes/org.wso2.carbon.andes/pom.xml, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceDataHolder.java, pom.xml
Changes related to https://wso2.org/jira/browse/MB-1276
=> Changes related to MB-1276

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/QueueManagementBeans.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/SubscriptionManagementBeans.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/retrieve_message_count_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/retrive_message_count_for_subscriber_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp
Fixing https://wso2.org/jira/browse/MB-1490
=> Fix wrong msg count on refresh

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
jira: https://wso2.org/jira/browse/MB-1584
=> [MB-1584] Change slotRetainTimeInMemory property in broker.xml in to a meaningful name

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
jira: https://wso2.org/jira/browse/MB-1554
A minor documentation improvement.
=> [MB-1554] A minor documentation improvement.

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/message_content.jsp
jira: https://wso2.org/jira/browse/MB-1595
=> [MB-1595] Fixing a UI issue

pom.xml
jira: https://wso2.org/jira/browse/MB-1561
=> [MB-1561]Upgrade carbon metrices lib

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/js/treecontrol.js
JIRA - https://wso2.org/jira/browse/MB-1565
=> [MB-1565] Modified DLC page to support higher number of messages to be deleted/rerouted/restored

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp
JIRA - https://wso2.org/jira/browse/MB-1456
=> [MB-1456] DLC name to be acquired through stub instead of query string.

components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/topic_add.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_add.jsp
JIRA - https://wso2.org/jira/browse/MB-1383
=> [MB-1383] Added length validation for topic and queue names in UI.

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Changes related to "adding compression to MB"
Please merge with: https://github.com/wso2/andes/pull/493/
=> [MB-1617] Adding lz4 compression to wso2 MB

pom.xml
jira : https://wso2.org/jira/browse/MB-1620
=> [MB-1620] upgrade guava to v 19

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Changing default value of allowCompression configuration from 'true' to 'false'
=> Changing default value of allowCompression configuration

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_message_destinations_list_retrieve_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/js/treecontrol.js, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_messages_ids_ajaxprocessor.jsp, features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
JIRA - https://wso2.org/jira/browse/MB-1657
=> [MB-1657] Added improvement to rereoute messages of a specific destination in DLC to a queue.

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
=> [MB-1664] Ability to detect Network partitions

components/andes/src/main/java/org/wso2/carbon/andes/core/store/rdbms/RDBMSConstants.java
jira: https://wso2.org/jira/browse/MB-1691
=> [MB-1691] Delete Messages from DLC queue when using postgreSQL

components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceDataHolder.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/listeners/BrokerLifecycleListener.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/service/QpidService.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/service/QpidServiceImpl.java
Expose an OSGi service to listen broker lifecycle events.
=> Add broker lifecycle listener

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
jira:  https://wso2.org/jira/browse/MB-1705
=> [MB-1705] Remove hardcoded cert types from andes

components/andes/src/main/java/org/wso2/carbon/andes/core/internal/configuration/modules/JKSStore.java
jira: https://wso2.org/jira/browse/MB-1705
=> [MB-1705] Remove hardcoded cert types from andes C5

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
- public JIRA URL https://wso2.org/jira/browse/MB-1712
=> MB-1712 issue fixed.

components/andes/src/main/java/org/wso2/carbon/andes/core/AndesBinding.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/inbound/InboundBindingEvent.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/inbound/InboundExchangeEvent.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/slot/Slot.java
Fixed Non-transient non-serializable instance field in serializable class
=> [MB-1722] Fix non-serialized objects in serialized classes issue in find bugs

components/andes/src/main/java/org/wso2/carbon/andes/core/AndesBinding.java, components/andes/src/main/java/org/wso2/carbon/andes/core/AndesExchange.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/cluster/coordination/ClusterNotification.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/cluster/coordination/hazelcast/custom/serializer/wrapper/HashmapStringTreeSetWrapper.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/cluster/coordination/hazelcast/custom/serializer/wrapper/TreeSetLongWrapper.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/cluster/coordination/hazelcast/custom/serializer/wrapper/TreeSetSlotWrapper.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/inbound/InboundBindingEvent.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/inbound/InboundExchangeEvent.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/slot/Slot.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/thrift/slot/gen/SlotInfo.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/thrift/slot/gen/SlotManagementService.java
added serialVersionUID in serializable classes. This issue was reported in find bugs under SE_NO_SERIALVERSIONID category.
=> [MB-1722] Fix issues in not declaring serialVersionUID in Serializable classes

components/andes/pom.xml, components/andes/src/main/java/org/wso2/carbon/andes/core/AndesChannel.java, components/andes/src/main/java/org/wso2/carbon/andes/core/internal/inbound/FlowControlManager.java, pom.xml
Suppress Findbugs warnings until evaluate changing globalBufferBasedFlowControlEnabled[1], flowControlEnabled[2] variables to volatile.
[1] [INFO] Inconsistent synchronization of org.wso2.carbon.andes.core.internal.inbound.FlowControlManager.globalBufferBasedFlowControlEnabled;
locked 66% of time [org.wso2.carbon.andes.core.internal.inbound.FlowControlManager$BufferBasedFlowControlTimeoutTask, org.wso2.carbon.andes.core.internal.inbound.FlowControlManager, org.wso2.carbon.andes.core.internal.inbound.FlowControlManager, org.wso2.carbon.andes.core.internal.inbound.FlowControlManager, org.wso2.carbon.andes.core.internal.inbound.FlowControlManager, org.wso2.carbon.andes.core.internal.inbound.FlowControlManager, org.wso2.carbon.andes.core.internal.inbound.FlowControlManager, …
=> [MB-1722] Suppress IS2_INCONSISTENT_SYNC issues reported in findbugs

components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/js/treecontrol.js, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/js/treecontrol.js, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_details.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_purge_ajaxprocessor.jsp
Public JIRA URL - https://wso2.org/jira/browse/MB-1725
=> MB-1725 issue fixed.

components/andes/src/main/java/org/wso2/carbon/andes/core/AndesKernelBoot.java
Simplify boolean condition check. reported by findbugs.
=> [MB-1722] Simplify boolean condition check RpC_REPEATED_CONDITIONAL_TEST

components/andes/src/main/java/org/wso2/carbon/andes/core/AndesKernelBoot.java, components/andes/src/main/java/org/wso2/carbon/andes/core/AndesUtils.java, components/andes/src/main/java/org/wso2/carbon/andes/core/store/rdbms/RDBMSMessageStoreImpl.java, components/andes/src/main/java/org/wso2/carbon/andes/core/store/rdbms/RDBMSStoreUtils.java
Remove unused methods reported by findbugs UPM_UNCALLED_PRIVATE_METHOD.
jira : https://wso2.org/jira/browse/MB-1722
=> [MB-1722] Remove unused private methods

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp
jira: https://wso2.org/jira/browse/MB-1739
=> [MB-1739] Unable to view messages in the DLC when more than 100 messages exists

features/andes/org.wso2.carbon.andes.server.feature/resources/dbscripts/mssql-mb.sql
Resolves the 2nd issue reported at https://wso2.org/jira/browse/MB-1773
=> [MB-1773] fixed issue in mssql script

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.admin/src/main/resources/META-INF/services.xml, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/SubscriptionManagerService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/SubscriptionManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/SubscriptionManagementBeans.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/SubscriptionManagementConstants.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/queue_subscriptions_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/retrive_message_count_for_subscriber_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp, service-stubs/org.wso2.carbon.andes.stub/src/main/resources/AndesAdminService.wsdl
Add all nodes search in clustered mode and avoid the duplicated entries in the connected node drop down and fix the message count refresh button.
Associated JIRA Link : https://wso2.org/jira/browse/MB-1778
=> [MB-1778] Fix subscription filtering and refresh button

components/andes/org.wso2.carbon.andes.authentication/src/main/java/org/wso2/carbon/andes/authentication/andes/oauth/OAuthTokenValidaterStubFactory.java
https://wso2.org/jira/browse/MB-1715
=> resolving configuration issue MB-1715

components/andes/org.wso2.carbon.andes.event.admin/src/main/java/org/wso2/carbon/andes/event/admin/AndesEventAdminService.java, components/andes/org.wso2.carbon.andes.event.admin/src/main/resources/META-INF/services.xml, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/TopicManagerService.java, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/TopicNode.java, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/subscription/registry/TopicManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/load_topic_details_from_bEnd_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/topic_list_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/topic_manage.jsp, components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/topics.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp, service-stubs/org.wso2.carbon.andes.event.stub/src/main/resources/AndesEventAdminService.wsdl
- Improved topic list page performace by paginating getChildren method
=> Feature added : Support paginated topic list page

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/queue_subscriptions_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp
Public jira : https://wso2.org/jira/browse/MB-1802
=> Added  total subscription count in the UI

components/andes/org.wso2.carbon.andes.cluster.mgt/src/main/resources/META-INF/services.xml
- Public JIRA URL https://wso2.org/jira/browse/MB-1780
=> MB-1780 issue fixed.

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp
Fix refresh button to update the shared subscription pending message count.
Associated JIRA Link: https://wso2.org/jira/browse/MB-1819
=> [MB-1819] Fix Refresh button for shared subscriptions

components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/SubscriptionManagerService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/SubscriptionManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/SubscriptionManagementBeans.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/queue_subscriptions_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/service/QpidService.java, features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
=> Code refactor

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp
Modified DLC queue browse page displaying from which we can filter messages.
Fixing: https://wso2.org/jira/browse/MB-1825
=> [MB-1825] Modified DLC queue browse page 

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Remove DLC message expiration configuration from broker.xml
Associated JIRA Link: https://wso2.org/jira/browse/MB-1767
=> [MB-1767] Remove DLC message expiration configuration from broker.xml

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/QueueManagementBeans.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/org/wso2/carbon/andes/ui/i18n/JSResources.properties, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_message_reroute_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_message_restore_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/js/treecontrol.js, service-stubs/org.wso2.carbon.andes.stub/src/main/resources/AndesAdminService.wsdl
Fix the NPE when to reroute/restore the expired messages from DLC.
Add the UI notification regarding the reroute/restore status.
Associated JIRA Link: https://wso2.org/jira/browse/MB-1829
Merge with https://github.com/wso2/andes/pull/730
=> [MB-1829] Fix reroute/restore expired messages from DLC

components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java
=> Use ServerShutdownHandler and ServerRestartHandler to detect a broker shutdown

components/andes/org.wso2.carbon.andes.authentication/src/main/java/org/wso2/carbon/andes/authentication/andes/oauth/OAuthTokenValidaterStubFactory.java
https://wso2.org/jira/browse/MB-1715
=> [MB-1715] Resolve configuration reading issue

features/andes/org.wso2.carbon.andes.server.feature/resources/dbscripts/h2-mb.sql
=> Add H2 database tables for distributed transactions

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.admin/src/main/resources/META-INF/services.xml, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/AndesException.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerException.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/SubscriptionManagerException.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/MessageStatusInformationBeans.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/QueueManagementBeans.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/registry/SubscriptionManagementBeans.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/util/AdministrativeManagementConstants.java, service-stubs/org.wso2.carbon.andes.stub/src/main/resources/AndesAdminService.wsdl
This operation is used to dump message status information via a curl call. Important for troubleshooting. 
Resolving issue [MB-1853](https://wso2.org/jira/browse/MB-1853 )
=> [MB-1853] Added messageStatusDump operation to AndesAdminService.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java, components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/service/andes/AndesAuthorizationPlugin.java
Public JIRA - https://wso2.org/jira/browse/MB-1867
=> Debug logs added to authorization classes

components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/builder/EventBrokerBuilder.java, components/andes/org.wso2.carbon.andes.ui/src/main/java/org/wso2/carbon/andes/ui/UIUtils.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_messages_list.jsp, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/service/QpidServiceImpl.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/utils/MessageBrokerDBUtil.java, pom.xml
Following fixes contain in this PR.
1. Fix conf path to be taken from system property.
2. [MB-1729] Added csrf token to POST method in more button in queue browse page.
=> Add fixes to release 3.1.15

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/subscriptions_close_ajaxprocessor.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp, service-stubs/org.wso2.carbon.andes.stub/src/main/resources/AndesAdminService.wsdl
Non durable topic subscriber connection closed through subscription list page. The subscriber connection closed without issue. But topic couldn't delete in the topic list page due to registry resource not getting cleared. The issue was user subject not passed to the authorization when closing the connection. This was fixed by changing the close connection and delete registry entry as two different calls.
Public JIRA - https://wso2.org/jira/browse/MB-1815
=> MB-1815 issue fixed.

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
- transaction/maxBatchSizeInKB : 1024 -> 10240
- transaction/maxParallelDtxChannels : 100 -> 10
=> Change transaction config defaults

components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/AndesAdminService.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/QueueManagerServiceImpl.java, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/queue_subscriptions_list.jsp
Fixed permission issue for closing queue and topic subscriptions in tenant mode.
=> Fix MB-1758

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
This depends on https://github.com/wso2/andes/pull/813
=> [MB-1865] Added necessary configs related to slot deletion to broker.xml.

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1886
The fix is to re-attempt authorization once a UsertStore exception is caught when authorizing.
=> [MB-1886] issue when adding bindings concurrently

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
Queue subscription not allowed to subscribe to other's queue unless consuming permission granted through the management console. But durable topic allowed to do it. Therefore, same behavior bring to the topic subscribers.
Public JIRA - https://wso2.org/jira/browse/MB-1897
=> MB-1897 issue fixed.

components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/builder/EventBrokerBuilder.java, components/andes/org.wso2.carbon.andes.ui/src/main/java/org/wso2/carbon/andes/ui/UIUtils.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/service/QpidServiceImpl.java, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/utils/MessageBrokerDBUtil.java, pom.xml
Porting : https://github.com/wso2/carbon-business-messaging/pull/383
=> Ei compatibility fixes

features/org.wso2.carbon.business.messaging.admin.services.feature/pom.xml
Replace wrong parent pom artifact id with correct id to resolve compilation failure.
=> Add correct parent pom Artifact Id in admin.services.feature

pom.xml
Fix missing dependency version issue.
=> Add missing testng dependency version

components/org.wso2.carbon.business.messaging.core/src/main/java/org/wso2/carbon/business/messaging/core/internal/ServiceComponent.java
Fix "WARN {org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver}" issue where ServiceComponent dose not starting up.
=> Fix osgi bundle StartupOrderResolver issue

features/org.wso2.carbon.business.messaging.core.feature/pom.xml, features/org.wso2.carbon.business.messaging.core.feature/src/main/java/configuration/MBConfigurations.java, pom.xml
Use carbon 5 based configuration model to generate MB 4 configs
=> Use carbon config generation to generate MB configs

pom.xml
> update andes version to 3.2.29
=> update andes version

pom.xml
Update andes dpendency to latest released version
Update parent pom with new andes dependency version
=> Update andes dependency version

pom.xml
Update Andes dependency version to 3.2.33.
=> Update Andes dependency version to 3.2.33

features/andes/org.wso2.carbon.andes.server.feature/pom.xml, pom.xml
Update the wso2-axis2-transport dependency to the latest version.
=> Update wso2-axis2-transport version

pom.xml
> Update Andes and Axis2 Transport versions for the latest versions.
=> Update Andes and Axis2 Transport versions

pom.xml
> Update andes and carbon commons versions to the latest versions
=> Update andes and commons versions

pom.xml
Upgraded axis2-transport version to 2.0.0-wso2v12
=> Upgrading axis2-transport version

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Task idle configuration added to broker.xml with the default value set to 100ms.
Resolves: wso2/product-ei#1826
Decreasing task idle time will effect on speed up delivery messages when publishers are slow. But system load will go up.
For an example change `<idleTaskDelay>10</idleTaskDelay>` in the broker.xml under `<slots>`
A user wants to gain subscribers performance when publishers are slow.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated …
=> fix product-ei/issues/1826

pom.xml
Update commons andes and axis2 transport dependency versions for the release
=> Update dependency versions for the release

pom.xml
Upgrade andes version for EI-6.1.1-Update22 release.
=> Upgrade andes version

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_messages_list.jsp
Improve queue browsing in Broker Profile UI
> Encode information when setting to jsp page
N/A - not a visible UI improvement 
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
N/A
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and …
=> Improve queue browsing in Broker Profile UI

pom.xml
This is to upgrade the andes version to 3.2.45.
> Link to the PR for changes to the training content in …
=> Upgrade andes version to 3.2.45

components/andes/org.wso2.carbon.andes.authentication/pom.xml, features/andes/org.wso2.carbon.andes.server.feature/pom.xml, pom.xml
This is to upgrade versions in carbon business messaging
1. kernel version
2. axis2 version
> Link to the PR for changes to the …
=>  Upgrade versions in carbon-business-messaging 

pom.xml
=> Upgrade kernel/identity versions

pom.xml
=> Upgrade to latest andes version

pom.xml
> Upgrade Andes version to 3.2.50
> Have latest Andes kernel in Andes feature
> Upgrade Andes version to 3.2.50
> N/A, Version upgrade
> Upgraded to latest Andes version
> N/A, Version upgrade
> N/A, Version upgrade
> N/A, Version upgrade
> N/A, Version upgrade
> N/A, Version upgrade
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> N/A, Version upgrade
> https://github.com/wso2/andes/pull/966
> N/A
> Fedora 23 x64, Oracle JDK 1.8.91
> N/A, Version upgrade
=> Upgrade Andes version to 3.2.50

pom.xml
Upgrade wso2-axis2-transport version to 2.0.0-wso2v16.
> Link(s) to product documentation that addresses the changes of this …
=> Upgrade transport version

pom.xml
This is to upgrade axis2 transport version
2.0.0-wso2v16 >> 2.0.0-wso2v17
> Link to the PR for changes to the training content in …
=> Upgrade axis2-transport version

pom.xml
Upgrade andes and axis2-transport versions
> Link to the PR for changes to the training content in …
=> Upgrade andes and axis2-transport versions

pom.xml
> Update the identity oauth version and the import version range
> Link to the PR for changes to the training content in …
=> Identity oauth version upgrade

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Introduce SSL protocols and cipher suites parameters for MQTT and AMQP transports in broker.xml.
Related issue: https://github.com/wso2/product-ei/issues/2365
> Brief description of the new feature or bug fix as it …
=> Introduce SSL configuring parameters

pom.xml
=> Upgrade commons, andes and axis2 trasnport version

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
> Add missing configs to broker.xml 
This fixes issue: https://github.com/wso2/product-ei/issues/2668
=> [EI - 2668] Add missing configs to broker.xml

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/AndesAuthorizationHandler.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the 
following format: Resolves issue1, issue2, etc.
Grants binding permission if a user has one of 'create_queue' or consume/publish permission for a queue.
Resolves https://github.com/wso2/product-ei/issues/2717
=> Fix permission issue on message publish

pom.xml
Updates andes dependency from 3.2.90 to 3.2.91
=> Update andes dependency

pom.xml
=> Upgrade asm version

pom.xml
=> Upgrade reflectasm version

components/andes/org.wso2.carbon.andes.event.ui/src/main/resources/web/topics/topic_add.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/dlc_messages_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/queue_subscriptions_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp
HTML-encode parameters to increase security.
=> update multiple JSP files

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/queues/queue_add.jsp
HTML-encode parameters to increase security.
=> carbon-andes-ui: update queue_add.jsp

components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/queue_subscriptions_list.jsp, components/andes/org.wso2.carbon.andes.ui/src/main/resources/web/subscriptions/topic_subscriptions_list.jsp
=> carbon-andes-ui: update topic/queue subscription_lists.jsp

pom.xml
=> Upgrade identity oauth version

components/andes/org.wso2.carbon.andes.admin.mqtt/pom.xml, components/andes/org.wso2.carbon.andes.admin.mqtt/src/main/java/org/wso2/carbon/andes/admin/mqtt/internal/AndesBrokerManagerMQTTAdminServiceDS.java, components/andes/org.wso2.carbon.andes.admin/pom.xml, components/andes/org.wso2.carbon.andes.admin/src/main/java/org/wso2/carbon/andes/admin/util/AndesBrokerManagerAdminServiceDS.java, components/andes/org.wso2.carbon.andes.authentication/pom.xml, components/andes/org.wso2.carbon.andes.authentication/src/main/java/org/wso2/carbon/andes/authentication/internal/AuthenticationServiceComponent.java, components/andes/org.wso2.carbon.andes.authorization/pom.xml, components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/internal/AuthorizationServiceComponent.java, components/andes/org.wso2.carbon.andes.cluster.mgt/pom.xml, components/andes/org.wso2.carbon.andes.cluster.mgt/src/main/java/org/wso2/carbon/andes/cluster/mgt/internal/ClusterManagerServiceComponent.java, components/andes/org.wso2.carbon.andes.commons/pom.xml, components/andes/org.wso2.carbon.andes.commons/src/main/java/org/wso2/carbon/andes/commons/internal/CommonsServiceComponent.java, components/andes/org.wso2.carbon.andes.core/pom.xml, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/ds/QueueManagerServiceDS.java, components/andes/org.wso2.carbon.andes.core/src/main/java/org/wso2/carbon/andes/core/internal/ds/SubscriptionManagerServiceDS.java, components/andes/org.wso2.carbon.andes.event.admin/pom.xml, components/andes/org.wso2.carbon.andes.event.admin/src/main/java/org/wso2/carbon/andes/event/admin/internal/EventAdminDS.java, components/andes/org.wso2.carbon.andes.event.core/pom.xml, components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/ds/EventBrokerBuilderDS.java, components/andes/org.wso2.carbon.andes/pom.xml, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java, pom.xml
=>  Change the scr doc comment to component annotation, Add java 11 changes

components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/delivery/jms/QpidJMSDeliveryManagerFactory.java, pom.xml
- Change the org.wso2.securevault version to 1.1.2
- Resolve the secrets usingMiscellaneousUtil.resolve() method.
- Depends on secure-vault jar update.
=> Add secure vault changes.

components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java, pom.xml
=> Update version for jdk11 support

components/andes/org.wso2.carbon.andes.event.core/src/main/java/org/wso2/carbon/andes/event/core/internal/ds/EventBrokerBuilderDS.java
=> change service component name

components/andes/org.wso2.carbon.andes.admin.mqtt/pom.xml, components/andes/org.wso2.carbon.andes.admin/pom.xml, components/andes/org.wso2.carbon.andes.authentication/pom.xml, components/andes/org.wso2.carbon.andes.authorization/pom.xml, components/andes/org.wso2.carbon.andes.commons/pom.xml, components/andes/org.wso2.carbon.andes.core/pom.xml, components/andes/org.wso2.carbon.andes.event.admin/pom.xml, components/andes/org.wso2.carbon.andes.event.core/pom.xml, components/andes/org.wso2.carbon.andes/pom.xml, features/andes/org.wso2.carbon.andes.feature/pom.xml, features/andes/org.wso2.carbon.andes.server.feature/pom.xml, features/andes/org.wso2.carbon.andes.ui.feature/pom.xml, features/metrics/org.wso2.carbon.messaging.metrics.feature/pom.xml, features/metrics/org.wso2.carbon.messaging.metrics.ui.feature/pom.xml, pom.xml
=> service component update

pom.xml
=> Update dependencies for EI

components/andes/org.wso2.carbon.andes.admin.mqtt/pom.xml, components/andes/org.wso2.carbon.andes.admin/pom.xml, components/andes/org.wso2.carbon.andes.authentication/pom.xml, components/andes/org.wso2.carbon.andes.authentication/src/main/java/org/wso2/carbon/andes/authentication/andes/CarbonBasedMQTTAuthenticator.java, components/andes/org.wso2.carbon.andes.authentication/src/main/java/org/wso2/carbon/andes/authentication/andes/CarbonBasedPrincipalDatabase.java, components/andes/org.wso2.carbon.andes.authentication/src/main/java/org/wso2/carbon/andes/authentication/andes/OAuth2BasedMQTTAuthenticator.java, components/andes/org.wso2.carbon.andes.authentication/src/main/java/org/wso2/carbon/andes/authentication/andes/oauth/OAuthTokenValidaterStubFactory.java, components/andes/org.wso2.carbon.andes.authorization/pom.xml, components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/andes/CarbonPermissionBasedMQTTAuthorizer.java, components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/service/andes/AndesAuthorizationPlugin.java, components/andes/org.wso2.carbon.andes.cluster.mgt.ui/pom.xml, components/andes/org.wso2.carbon.andes.cluster.mgt/pom.xml, components/andes/org.wso2.carbon.andes.commons/pom.xml, components/andes/org.wso2.carbon.andes.core/pom.xml, components/andes/org.wso2.carbon.andes.event.admin/pom.xml, components/andes/org.wso2.carbon.andes.event.core/pom.xml, components/andes/org.wso2.carbon.andes.event.ui/pom.xml, components/andes/org.wso2.carbon.andes.ui/pom.xml, components/andes/org.wso2.carbon.andes/pom.xml, components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/listeners/MessageBrokerTenantManagementListener.java, pom.xml
- remove maven src plugin
- update log4j
=> Update Log4j version

components/andes/org.wso2.carbon.andes.admin.mqtt/pom.xml, components/andes/org.wso2.carbon.andes.admin/pom.xml, components/andes/org.wso2.carbon.andes.authentication/pom.xml, components/andes/org.wso2.carbon.andes.authorization/pom.xml, components/andes/org.wso2.carbon.andes.cluster.mgt/pom.xml, components/andes/org.wso2.carbon.andes.commons/pom.xml, components/andes/org.wso2.carbon.andes.core/pom.xml, components/andes/org.wso2.carbon.andes.event.admin/pom.xml, components/andes/org.wso2.carbon.andes.event.core/pom.xml, components/andes/org.wso2.carbon.andes/pom.xml, pom.xml
> This PR will add scr plugin to the broker components.
=> Add scr plugin to the broker components

pom.xml
> This PR will update the dependency versions regarding to the kernel upgrade.
=> Update dependency versions regarding to the kernal upgrade

pom.xml
> This PR will update the dependency versions for kernel upgrade(4.5.3).
=> Update dependency versions for kernel upgrade(4.5.3)

pom.xml
=> Bump kernel import range

pom.xml
Update versions to avoid duplicate versions in EI
=> Update versions to avoid duplicate versions in EI

pom.xml
=> Fix release build failure

features/andes/org.wso2.carbon.andes.server.feature/resources/conf/broker.xml
Add configuration to resolve: https://github.com/wso2/product-ei/issues/5322
=> Add thriftServerMaxWorkerThreads

components/andes/org.wso2.carbon.andes/src/main/java/org/wso2/carbon/andes/internal/QpidServiceComponent.java
This is to fix wso2/product-apim#10198
MQTT transport is disabled by default in APIM
=> Change log level to fix APIM:10198

pom.xml
update disruptor version to 3.4.2.wso2v1
=> update disruptor version to 3.4.2.wso2v1

pom.xml
=> Updating andes version

pom.xml
This PR upgrades protobuf-java version to `3.19.3`.
=> Upgrade protobuf-java version

pom.xml
=> Upgrade guava version to 31.0.1-jre

features/andes/org.wso2.carbon.andes.server.feature/pom.xml, pom.xml
=> Upgrade commons-beanutils to 1.9.4

components/andes/org.wso2.carbon.andes.authorization/src/main/java/org/wso2/carbon/andes/authorization/service/andes/AndesAuthorizationPlugin.java, components/andes/org.wso2.carbon.andes.commons/src/main/java/org/wso2/carbon/andes/commons/CommonsUtil.java, pom.xml
> Fixes : https://github.com/wso2/api-manager/issues/1858 along with https://github.com/wso2/andes/pull/1057
=> Add function to check of authorization is required for AMQP from broker.xml level

pom.xml
Upgrade guava version to 32.1.2-jre
=> Upgrade guava version to 32.1.2-jre

features/andes/org.wso2.carbon.andes.server.feature/pom.xml, pom.xml
$Subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Upgrading h2 version

pom.xml
Upgraded following dependencies
sqlite -> 3.44.1.0
guava -> 33.0.0-jre
=> Upgrade sqlite version
